name = "§lNewb X §6Pineapple"
version = [0, 3, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§7An aesthetic shader with a chill color theme§r
%v
§c%w
''' # %w = patch warning, %v = version
authors = ["firmw4", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "12d4ea4a-7439-4969-b936-9ad0d511d7d1" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

[custom]
label = '''
・Recommended set brightness to 30-40
・Don't use experimental features and education mode (or some bugs will occur)
・Disable Vsync for better performance
・Use ESSL300 fix lag pack for Snapdragon devices to reduce sutter and lag spike issue
・§csome devices specifically experience a bug in cloud cut render§r

    §lCopyright (c)§r
§cRedistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.§r

To find out about shader changes and updates, visit our discord server:
https://discord.com/invite/chM7qTrGJT
§lThanks for downloading and using this shader :)§r
'''
input = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "VOLUMETRIC_CLOUDS"
materials = ["RenderChunk", "Clouds"]
description = '''
§4Ultra Pack§r

Summary: Realistic clouds style, always reflection and aurora reflection 
§cImportant! Some devices with certain GPUs are not compatible with this cloud style§r
'''

[[subpack]]
define = "ALWAYS_REFLECTION"
materials = ["RenderChunk"]
description = '''
§bAlways Reflection

Summary: Enable reflection effect at ground
'''

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["RenderChunk", "Clouds"]
description = '''
§9Rounded Clouds§r

Summary: Change to rounded clouds style
'''

[[subpack]]
define = "SIMPLE_CLOUDS"
materials = ["RenderChunk", "Clouds"]
description = '''
§6Simple Clouds§r

Summary: Change to simple clouds style
'''

[[subpack]]
define = "RAINBOWS"
materials = ["Sky"]
description = '''
§4R§6a§ei§an§2b§1o§5w§ds§r

Summary: Show rainbow effect on sky
'''

[[subpack]]
define = "NIGHT_VISION"
materials = ["RenderChunk"]
description = '''
§eNight Vision§r

Summary: Full bright at night
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
§aNo Wave§r

Summary: Disable wave effect
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default

Summary: Vanilla clouds, wave effect and aurora at night
'''
